# Generated by Django 5.1.6 on 2025-02-18 16:47

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], default=1, max_length=10, verbose_name='الحالة الاجتماعية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=django_countries.fields.CountryField(default='SA', max_length=2, verbose_name='الجنسية'),
            preserve_default=False,
        ),
    ]
