# Generated by Django 5.1.6 on 2025-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_job_student_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='companion_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المرافق'),
        ),
        migrations.AddField(
            model_name='student',
            name='companion_nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جنسية المرافق'),
        ),
        migrations.AddField(
            model_name='student',
            name='companion_passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم جواز المرافق'),
        ),
        migrations.AddField(
            model_name='student',
            name='companion_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='student',
            name='companion_residence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء إقامة المرافق'),
        ),
        migrations.AddField(
            model_name='student',
            name='companion_residence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم إقامة المرافق'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_issued',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة'),
        ),
        migrations.AddField(
            model_name='student',
            name='end_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التسجيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول'),
        ),
        migrations.AddField(
            model_name='student',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الجهة المصدرة'),
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الجواز'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الإصدار'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_issued_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان إصدار الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='port_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الميناء'),
        ),
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرض'),
        ),
        migrations.AddField(
            model_name='student',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان التسجيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_issue_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان إصدار الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإقامة'),
        ),
        migrations.AddField(
            model_name='student',
            name='type_of_services',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الخدمات'),
        ),
        migrations.AddField(
            model_name='student',
            name='visa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التأشيرة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='الجنسية'),
        ),
    ]
