# Generated by Django 5.1.6 on 2025-03-01 23:09

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_companion_name_student_companion_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='الجنسية'),
        ),
    ]
