# Generated by Django 5.1.6 on 2025-03-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_name_alter_student_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
