# Generated by Django 5.2.1 on 2025-06-04 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'جواز سفر'), ('residence', 'إقامة'), ('id_card', 'هوية شخصية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='student_docs/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='الطالب')),
            ],
        ),
    ]
