# Generated by Django 5.2.1 on 2025-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='الوصف التوضيحي'),
        ),
    ]
