# Generated by Django 5.2.1 on 2025-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_correspondent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondent',
            options={'verbose_name': 'الاسم', 'verbose_name_plural': 'إدارة التوجيهات والمراسلات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_create_correspondence', 'Can create correspondence/letters')]},
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number_old',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
