# Generated by Django 5.2.1 on 2025-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_correspondent_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='توقيع المدير التنفيذي'),
        ),
    ]
