# Generated by Django 5.2.1 on 2025-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_correspondent_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدير التنفيذي')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='المنصب الوظيفي')),
                ('Institute', models.CharField(blank=True, max_length=100, verbose_name='اسم المعهد')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='توقيع المدير التنفيذي')),
            ],
            options={
                'verbose_name': 'المدير التنفيذي',
                'verbose_name_plural': 'المدير التنفيذي',
            },
        ),
        migrations.RemoveField(
            model_name='correspondent',
            name='signature',
        ),
    ]
