# Generated by Django 5.2.1 on 2025-06-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_executivedirector_remove_correspondent_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executivedirector',
            options={'verbose_name': 'المدير التنفيذي', 'verbose_name_plural': 'بيانات المدير التنفيذي'},
        ),
        migrations.RenameField(
            model_name='executivedirector',
            old_name='Institute',
            new_name='institute',
        ),
    ]
