# Generated by Django 5.2.1 on 2025-06-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_executivedirector_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type_code', models.CharField(max_length=20, unique=True, verbose_name='رمز نوع الخطاب')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='آخر رقم تسلسلي')),
            ],
            options={
                'verbose_name': 'عدّاد أرقام مرجعية',
                'verbose_name_plural': 'عدّادات الأرقام المرجعية',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_create_correspondence', 'Can create correspondence/letters')], 'verbose_name': 'الطالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم المرجعي')),
                ('letter_type', models.CharField(max_length=50, verbose_name='نوع الخطاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('students', models.ManyToManyField(to='students.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'خطاب مُنشأ',
                'verbose_name_plural': 'الخطابات المُنشأة',
                'ordering': ['-created_at'],
            },
        ),
    ]
