# Generated by Django 5.2.1 on 2025-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_referencecounter_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='الاسم الأوسط'),
        ),
    ]
