# Generated by Django 5.2.1 on 2025-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reference_number_int',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(editable=False, max_length=5, null=True, verbose_name='الرقم المرجعي'),
        ),
    ]
