# Generated by Django 5.2.1 on 2025-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_fill_reference_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number_old',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الجواز القديم'),
        ),
    ]
