# Generated by Django 5.2.1 on 2025-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_student_passport_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_issued',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اصدار الجواز'),
        ),
    ]
